### ISSUE TITLE
Lazy loading of Helpers

### ISSUE THREAD

**Issue by markomarkovic** [predominant/TwigView#13]
When using the default View class, helpers are automatically loaded when used. With TwigView, they're not loaded unless explicitly declared in the controller. e.g. `public $helpers = array('Html', 'Form');`.

Is there a way to do this automatically, like in the original View class?

**Comment by predominant** [comment]
There is a way to fix this. Tinkering at the moment.

**Comment by predominant** [comment]
Kinda left that one without fixing it. Sorry @markomarkovic!
