### ISSUE TITLE
"Element Not Found: Elements/xxxx.ctp" in Session.flash

### ISSUE THREAD

**Issue by STAR-ZERO** [predominant/TwigView#16]
If you use a custom element in session.flash "Element Not Found: Elements/xxxx.ctp" occurs.
I want to use the tpl extension, "Elements/xxxx.tpl".

Controller:

```
$this->Session->setFlash($message, 'xxxx', array());
```

View:

```
{{ _view.Session.flash() }}
```

I use CakePHP 2.3.x

**Comment by mcreenan** [comment]
For some reason, the element method in TwigView.php has a condition to change the extension to .ctp in some scenarios.   I comment that out without any issues.

**Comment by predominant** [comment]
Thanks for that comment. I've removed the weird element rendering hack. Thats produced good results for me, let me know what you think.
