### ISSUE TITLE
How to extend a template

### ISSUE THREAD

**Issue by ponyjoy** [predominant/TwigView#20]
|----Post
|---------index.tpl
|---------mytemplate.tpl
## index.tpl:

{% extends 'mytemplate.tpl' %}
{% block title %}
Hello,World!
{% endblock %}
## mytemplate.tpl

{% block title %}
This is title
{% endblock %}

PostController
  public function index()
  {  
        return $this->render("index");
   }

I got an error:
Unable to find template "mytemplate.tpl" (looked into: G:\PHP\WWW\cakephp\app\View).

How to resolve it?

**Comment by ponyjoy** [comment]
It wors. Just use
{% extends '/Post/mytemplate.tpl' %}

**Comment by predominant** [comment]
Thanks for posting the issue, and your findings, as well as closing the ticket :) nice work
