### ISSUE TITLE
Is not possible use the blocks?

### ISSUE THREAD

**Issue by matheusmatos** [predominant/TwigView#24]
For example, in the view Layout:

``` html
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
```

After, in the view:

``` html
{% extends 'Layout/default.tpl' %}
{% block title %}
    My Title by the view!!
{% endblock %}
```

How I do it?

**Comment by WaldekC** [comment]
It is, but not in the way you are trying, first create your base layout, call it Layout/base.tpl,  move content from default.tpl to base.tpl. 

Next in default.tpl:

``` php
{{ _view.fetch('content') }}
```

and you can use `extends` in view like:

``` php
{% extends 'Layout/base.tpl' %}
{% block title %}
    My Title by the view!!
{% endblock %}
```

**Comment by matheusmatos** [comment]
Hello WaldekC, I'll try by this way.
Thank you very much!!
